use_frameworks!

platform :ios, '10.0'

target 'MYIOSAdsDdcxSDK_Example' do
  pod 'MYIOSAdsDdcxSDK', :path => '../'

  target 'MYIOSAdsDdcxSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
